using UnityEngine;

/// <summary>
/// Runtime marker generated by HauntedHouseBuilder for rooms, patrol routes,
/// monster spawns, and safe recovery points.
/// </summary>
public class HouseZone : MonoBehaviour
{
    public enum ZoneKind
    {
        Room,
        Corridor,
        MonsterSpawn,
        Patrol,
        Recovery
    }

    [SerializeField] string zoneId;
    [SerializeField] ZoneKind kind;
    [SerializeField] Vector3 size = new Vector3(2f, 2.5f, 2f);

    public string ZoneId => zoneId;
    public ZoneKind Kind => kind;
    public Vector3 Size => size;

    public void Configure(string id, ZoneKind zoneKind, Vector3 zoneSize)
    {
        zoneId = id;
        kind = zoneKind;
        size = new Vector3(
            Mathf.Max(0.25f, zoneSize.x),
            Mathf.Max(0.25f, zoneSize.y),
            Mathf.Max(0.25f, zoneSize.z));

        var trigger = GetComponent<BoxCollider>();
        if (trigger == null)
            trigger = gameObject.AddComponent<BoxCollider>();
        trigger.isTrigger = true;
        trigger.size = size;
    }

#if UNITY_EDITOR
    void OnDrawGizmosSelected()
    {
        Gizmos.color = kind switch
        {
            ZoneKind.MonsterSpawn => new Color(0.8f, 0.1f, 0.1f, 0.35f),
            ZoneKind.Patrol => new Color(0.9f, 0.6f, 0.1f, 0.35f),
            ZoneKind.Recovery => new Color(0.1f, 0.8f, 0.8f, 0.35f),
            ZoneKind.Corridor => new Color(0.3f, 0.5f, 0.9f, 0.25f),
            _ => new Color(0.4f, 0.9f, 0.4f, 0.25f)
        };
        Gizmos.matrix = transform.localToWorldMatrix;
        Gizmos.DrawCube(Vector3.zero, size);
        Gizmos.DrawWireCube(Vector3.zero, size);
    }
#endif
}
